"""baseline schema

Revision ID: daa6c55ad888
Revises: 
Create Date: 2026-06-27 16:37:53.333453
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa6c55ad888'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dist_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('office', sa.Integer(), nullable=False),
    sa.Column('last_successful_fetch', sa.DateTime(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'dist_id', 'status', 'office', name='api_request_uniq')
    )
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('created_year', sa.Integer(), nullable=True),
    sa.Column('petitioner_name', sa.String(), nullable=True),
    sa.Column('petitioner_mobile', sa.String(), nullable=True),
    sa.Column('petitioner_email', sa.String(), nullable=True),
    sa.Column('petitioner_gender', sa.String(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('grievance', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('received_by', sa.String(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.Column('disability', sa.String(), nullable=True),
    sa.Column('disability_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('complaint_status_id', sa.Integer(), nullable=True),
    sa.Column('govt_ticket', sa.Boolean(), nullable=True),
    sa.Column('transfer_status', sa.String(), nullable=True),
    sa.Column('urgent', sa.String(), nullable=True),
    sa.Column('benefitted', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('dept', sa.String(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('tagged_to', sa.String(), nullable=True),
    sa.Column('tagged_by', sa.String(), nullable=True),
    sa.Column('tagged_by_id', sa.String(), nullable=True),
    sa.Column('tagged_date', sa.DateTime(), nullable=True),
    sa.Column('pending_with', sa.String(), nullable=True),
    sa.Column('pending_with_id', sa.Integer(), nullable=True),
    sa.Column('review_authority', sa.String(), nullable=True),
    sa.Column('review_authority_id', sa.Integer(), nullable=True),
    sa.Column('all_esc_user', sa.String(), nullable=True),
    sa.Column('self_assign', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('assigned_on', sa.DateTime(), nullable=True),
    sa.Column('escalation_date', sa.DateTime(), nullable=True),
    sa.Column('resolved_on', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('last_updated_on', sa.DateTime(), nullable=True),
    sa.Column('reopened_by', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('local_document_path', sa.String(), nullable=True),
    sa.Column('document_downloaded', sa.Boolean(), nullable=True),
    sa.Column('document_download_date', sa.DateTime(), nullable=True),
    sa.Column('document_download_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no'),
    sa.UniqueConstraint('ticket_no', name='ticket_no_uniq')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dist_name', sa.String(), nullable=False),
    sa.Column('dist_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dist_id'),
    sa.UniqueConstraint('dist_id', name='dist_id_uniq')
    )
    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(), nullable=True),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('action_taken_date', sa.DateTime(), nullable=True),
    sa.Column('action_taken_by', sa.String(), nullable=True),
    sa.Column('action_status', sa.String(), nullable=True),
    sa.Column('action_taken_remark', sa.String(), nullable=True),
    sa.Column('complaint_status_with_authority', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_no'], ['complaints.ticket_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no', 'action_taken_by', 'action_status', 'action_taken_remark', 'complaint_status_with_authority', name='action_history_uniq')
    )
    op.create_table('action_history_api_request_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(), nullable=True),
    sa.Column('last_successful_fetch', sa.DateTime(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_no'], ['complaints.ticket_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no', name='action_history_api_request_uniq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_history_api_request_tracking')
    op.drop_table('action_history')
    op.drop_table('districts')
    op.drop_table('complaints')
    op.drop_table('api_request_tracking')
    # ### end Alembic commands ###
