"""Generate the Odisha district hotspot map partial for the value-add deck.

Reads two committed aggregate files and writes a self-contained Quarto partial
with the district outlines already projected to SVG path data:

    assets/data/odisha-districts.geojson   30 district boundaries, WGS84
    assets/data/district-counts.json       complaint counts by district x category
    -> assets/_hotspot-map.qmd

Both inputs are aggregates and carry no citizen data, so **rebuilding the deck
never touches `data/`**. Regenerating the inputs themselves does, and is a
separate, deliberate step -- see the header of `assets/data/README.md`.

Projection is equirectangular with a cos(lat) correction at Odisha's mean
latitude. At this extent the difference from a proper equal-area projection is
smaller than the 6 km simplification tolerance already applied to the outlines,
and it keeps the runtime dependency-free: the slide gets plain `<path>` data and
needs no projection library, no deck.gl and no network.

    uv run python scripts/build_deck_map.py
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

DECK = Path("docs/presentations/2026-08-17-value-add")
WIDTH = 1000.0
PAD = 8.0

# Colour ramp from the deck palette: ivory through to DPIC maroon. Five bins,
# because more than five is not readable from the back of a room.
RAMP = ["#F2F0E9", "#E3C9CB", "#CE9AA0", "#B26674", "#8B1524"]


def _rings(geometry: dict) -> list[list[list[float]]]:
    kind, coords = geometry["type"], geometry["coordinates"]
    if kind == "Polygon":
        return coords
    if kind == "MultiPolygon":
        return [ring for polygon in coords for ring in polygon]
    raise ValueError(f"unsupported geometry {kind!r}")


def build(deck: Path) -> Path:
    geo = json.loads((deck / "assets/data/odisha-districts.geojson").read_text())
    counts = json.loads((deck / "assets/data/district-counts.json").read_text())

    lons = [p[0] for f in geo["features"] for r in _rings(f["geometry"]) for p in r]
    lats = [p[1] for f in geo["features"] for r in _rings(f["geometry"]) for p in r]
    lon0, lon1, lat0, lat1 = min(lons), max(lons), min(lats), max(lats)
    kx = math.cos(math.radians((lat0 + lat1) / 2))
    scale = (WIDTH - 2 * PAD) / ((lon1 - lon0) * kx)
    height = (lat1 - lat0) * scale + 2 * PAD

    paths = []
    for feature in sorted(geo["features"], key=lambda f: f["properties"]["d"]):
        name = feature["properties"]["d"]
        d = []
        for ring in _rings(feature["geometry"]):
            pts = [
                f"{PAD + (lon - lon0) * kx * scale:.1f},"
                f"{height - PAD - (lat - lat0) * scale:.1f}"
                for lon, lat in ring
            ]
            d.append("M" + "L".join(pts) + "Z")
        paths.append(f'<path class="hs-d" data-d="{name}" d="{"".join(d)}"></path>')

    cats = counts["categories"]
    buttons = "".join(
        f'<button data-cat="{c}"{" class=\"active\"" if i == 0 else ""}>{c}</button>'
        for i, c in enumerate(cats)
    )

    body = f"""```{{=html}}
<!--
  GENERATED by scripts/build_deck_map.py. Do not hand-edit; re-run the script.
  District outlines are pre-projected to SVG path data at build time, so this
  needs no projection library, no deck.gl and no network at presentation time.
-->
<div class="hotspot" id="hotspot">
  <div class="hs-controls">
    <div class="hs-seg" id="hs-seg">{buttons}</div>
    <div class="hs-legend" id="hs-legend"></div>
  </div>
  <svg class="hs-map" viewBox="0 0 {WIDTH:.0f} {height:.0f}" preserveAspectRatio="xMidYMid meet">
    {"".join(paths)}
  </svg>
  <div class="hs-readout" id="hs-readout">Hover a district</div>
</div>

<script>
(function () {{
  var COUNTS = {json.dumps(counts["districts"], separators=(",", ":"))};
  var RAMP = {json.dumps(RAMP)};
  var root = document.getElementById("hotspot");
  if (!root) return;
  var readout = document.getElementById("hs-readout");
  var legend = document.getElementById("hs-legend");
  var cat = "{cats[0]}";

  function values(c) {{
    return Object.keys(COUNTS).map(function (d) {{ return COUNTS[d][c] || 0; }});
  }}
  // Quantile bins, not equal-width. Complaint counts are heavily skewed, and
  // equal-width bins put 27 districts in the palest bucket and say nothing.
  function breaks(c) {{
    var v = values(c).slice().sort(function (a, b) {{ return a - b; }});
    return [0.2, 0.4, 0.6, 0.8].map(function (q) {{ return v[Math.floor(q * (v.length - 1))]; }});
  }}
  function bin(n, br) {{
    for (var i = 0; i < br.length; i++) {{ if (n <= br[i]) return i; }}
    return br.length;
  }}
  function paint() {{
    var br = breaks(cat);
    root.querySelectorAll(".hs-d").forEach(function (p) {{
      var n = (COUNTS[p.dataset.d] || {{}})[cat] || 0;
      p.style.fill = RAMP[bin(n, br)];
    }});
    legend.innerHTML = '<span class="hs-lk">fewer</span>' +
      RAMP.map(function (c) {{ return '<i style="background:' + c + '"></i>'; }}).join("") +
      '<span class="hs-lk">more</span>';
  }}

  root.querySelectorAll(".hs-d").forEach(function (p) {{
    p.addEventListener("mouseenter", function () {{
      var e = COUNTS[p.dataset.d] || {{}};
      var n = e[cat] || 0, all = e.All || 0;
      var share = all ? (100 * n / all).toFixed(1) + "% of the district's filings" : "";
      readout.innerHTML = "<b>" + p.dataset.d + "</b> &middot; " +
        n.toLocaleString() + " " + (cat === "All" ? "filings" : cat.toLowerCase() + " filings") +
        (cat === "All" ? "" : " &middot; " + share);
    }});
  }});
  root.addEventListener("mouseleave", function () {{ readout.textContent = "Hover a district"; }});

  document.getElementById("hs-seg").addEventListener("click", function (ev) {{
    var b = ev.target.closest("button");
    if (!b) return;
    cat = b.dataset.cat;
    this.querySelectorAll("button").forEach(function (x) {{ x.classList.remove("active"); }});
    b.classList.add("active");
    paint();
  }});

  paint();
}})();
</script>
```
"""
    out = deck / "assets/_hotspot-map.qmd"
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deck", type=Path, default=DECK)
    args = parser.parse_args()
    out = build(args.deck)
    print(f"wrote {out} ({out.stat().st_size / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
