"""Rebuild the pre-annotation draft for a gold file, from the gold's own text.

`bootstrap_pii_gold.py` writes a draft whose spans are exactly
``detect_pii_spans(text)`` for each page. That makes the draft's *labels* a pure
function of its *text* plus the pinned analyzer, so if the text survives the
draft can be rebuilt. The gold carries that text, because the annotation pass
edits spans and leaves the text alone.

Why this exists: the OCR half of bootstrap is not reproducible across machines
(#57), so a lost draft cannot be regenerated by re-running bootstrap. It can be
rebuilt here, exactly, with no OCR involved.

Verified on a real draft before this script was written: re-deriving from the
draft's own text reproduced 573 of 573 spans across all 85 records.

What a re-derived draft is good for:

- the span-level audit of the human pass, which is the whole reason the draft is
  kept: what was added, deleted, re-bounded, relabelled.

What it cannot do, and `verify_pii_gold.py` will not tell you:

- **Prove the human pass happened.** It cannot fail. The gold is compared against
  analyzer output on the gold's own text, which is what the scorecard already
  measures, so read the recall number instead.
- **Detect a text edit.** The text is copied from the gold, so the text-equality
  check passes by construction.
- **Detect pages dropped from the drafted sample.** Record ids come from the
  gold, so the completeness check passes by construction. Only the original
  draft records which pages were drafted.

Both files are DVC-tracked and never enter git. Nothing here prints citizen text.

Usage:
    uv run --extra pii python scripts/rederive_pii_draft.py \
        --gold data/external/pii_gold_n50.jsonl \
        --out data/external/pii_gold_n50.rederived_draft.jsonl

Writes `<out>.provenance.json` alongside, recording the analyzer versions and the
gold checksum this was derived from. Without it a draft cannot be told apart
from a real bootstrap draft, and the caveats above would be invisible.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import importlib.util
import json
import platform
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Iterable, Sequence

_SCRIPT_DIR = Path(__file__).resolve().parent
PROVENANCE_SCHEMA_VERSION = "janasunani.pii-rederived-draft-provenance/v1"

# Reuse bootstrap's writer rather than reimplementing it: the on-disk format is a
# contract with pii_eval's loader (tests/test_bootstrap_pii_gold.py), and a
# re-derived draft has to be indistinguishable in shape from a real one.
_spec = importlib.util.spec_from_file_location(
    "bootstrap_pii_gold", _SCRIPT_DIR / "bootstrap_pii_gold.py"
)
_bootstrap = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = _bootstrap
_spec.loader.exec_module(_bootstrap)
spans_to_jsonl_line = _bootstrap.spans_to_jsonl_line


def load_records(path: Path) -> list[dict[str, Any]]:
    """Gold JSONL as raw dicts. Only `id` and `text` are used."""
    records = []
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip():
                continue
            raw = json.loads(line)
            if "text" not in raw:
                raise ValueError(f"{path}:{line_number}: missing 'text'")
            raw.setdefault("id", f"line-{line_number}")
            records.append(raw)
    if not records:
        raise ValueError(f"{path}: no records")
    ids = [str(r["id"]) for r in records]
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    if duplicates:
        raise ValueError(f"{path}: duplicate record ids: {duplicates[:5]}")
    return records


def rederive(
    records: Iterable[dict[str, Any]],
    predict: Callable[[str], Sequence[Any]],
) -> tuple[list[str], Counter]:
    """Draft JSONL lines for `records`, and a span count per entity."""
    lines: list[str] = []
    by_entity: Counter = Counter()
    for record in records:
        spans = predict(record["text"])
        for span in spans:
            by_entity[span.entity] += 1
        lines.append(spans_to_jsonl_line(str(record["id"]), record["text"], spans))
    return lines, by_entity


def _file_md5(path: Path) -> str:
    digest = hashlib.md5()  # noqa: S324 - matches the DVC pointer's own checksum
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _version(*candidates: str) -> str:
    for name in candidates:
        try:
            return importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:
            continue
    return "unknown"


def _git_commit() -> str:
    """The commit that produced this draft, suffixed -dirty if it was uncommitted.

    Pathspecs resolve against the process working directory, so `-C scripts`
    turned `janasunani` and `scripts` into `scripts/janasunani` and
    `scripts/scripts`, which match nothing. Every draft was therefore recorded
    as clean, attributing output to committed code that may not have produced
    it. Run from the repository root so the pathspecs mean what they say.
    """
    try:
        root = subprocess.run(
            ["git", "-C", str(_SCRIPT_DIR), "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        out = subprocess.run(
            ["git", "-C", root, "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        commit = out.stdout.strip()
        dirty = subprocess.run(
            ["git", "-C", root, "status", "--porcelain", "--", "janasunani", "scripts"],
            capture_output=True,
            text=True,
            check=True,
        )
        return f"{commit}-dirty" if dirty.stdout.strip() else commit
    except (subprocess.CalledProcessError, OSError):
        return "unknown"


def provenance(gold: Path, out: Path, records: int, by_entity: Counter) -> dict[str, Any]:
    """What a reader needs to know before trusting this file as a draft."""
    return {
        "schema_version": PROVENANCE_SCHEMA_VERSION,
        "kind": "rederived_draft",
        "note": (
            "Analyzer output on the gold's own text, NOT the original bootstrap "
            "draft. Cannot prove the human pass happened, cannot detect an edited "
            "text, cannot detect pages dropped from the drafted sample. See "
            "scripts/rederive_pii_draft.py."
        ),
        "created_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "out": out.name,
        "source_gold": gold.name,
        "source_gold_md5": _file_md5(gold),
        "records": records,
        "spans": sum(by_entity.values()),
        "spans_by_entity": dict(sorted(by_entity.items())),
        "analyzer": {
            "git_commit": _git_commit(),
            "presidio_analyzer": _version("presidio-analyzer", "presidio_analyzer"),
            "spacy": _version("spacy"),
            "en_core_web_sm": _version("en-core-web-sm", "en_core_web_sm"),
        },
        "environment": {
            "python": platform.python_version(),
            "system": platform.system(),
            "machine": platform.machine(),
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gold", type=Path, required=True, help="Corrected gold JSONL")
    parser.add_argument("--out", type=Path, required=True, help="Draft JSONL to write")
    parser.add_argument(
        "--force", action="store_true", help="Overwrite --out if it already exists"
    )
    args = parser.parse_args()

    # --force exists to overwrite a stale draft. Pointed at the gold it would
    # overwrite irreplaceable human labelling with analyzer output, and the
    # checksum below would then hash the destroyed file and record it as the
    # source. No flag makes that recoverable, so it is refused outright.
    if args.out.resolve() == args.gold.resolve():
        sys.exit(
            f"--out is the same file as --gold ({args.gold}). Refusing: this would "
            "overwrite the corrected gold with analyzer output and cannot be undone."
        )

    if args.out.exists() and not args.force:
        sys.exit(
            f"{args.out} exists. Refusing to overwrite: if it is the ORIGINAL "
            "bootstrap draft it cannot be regenerated (#57). Pass --force only "
            "once you are certain it is not."
        )

    from janasunani.pipeline.stages.pii_tagger import detect_pii_spans

    records = load_records(args.gold)
    lines, by_entity = rederive(records, detect_pii_spans)

    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    meta = provenance(args.gold, args.out, len(records), by_entity)
    sidecar = args.out.with_suffix(args.out.suffix + ".provenance.json")
    sidecar.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {args.out}")
    print(f"  records : {meta['records']}")
    print(f"  spans   : {meta['spans']}  {meta['spans_by_entity']}")
    print(f"wrote {sidecar}")
    print(
        "\nThis is a RE-DERIVED draft. It cannot prove the human pass happened: "
        "the gold\nis being compared against analyzer output on its own text. "
        "Use it for the\nspan-level audit only, and read recall off the scorecard."
    )


if __name__ == "__main__":
    main()
